name: betterme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  firebase_storage: ^13.4.1
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^18.0.0
  image_picker: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.5+1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/Icon.png

flutter_launcher_icons:
  image_path: "assets/icon/Icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/Icon.png"
  windows:
    generate: true
    image_path: "assets/icon/Icon.png"
    icon_size: 256
