// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpS1SqtrRF3VurhnxR_im1TrYk7lE-RwI',
    appId: '1:68735913810:web:f0fd059ed849c1974db48b',
    messagingSenderId: '68735913810',
    projectId: 'betterme-43573',
    authDomain: 'betterme-43573.firebaseapp.com',
    storageBucket: 'betterme-43573.firebasestorage.app',
    measurementId: 'G-TPVDQDM7FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_ISSabGUzLPbKkw5HQP_4vDwZRBsI3U',
    appId: '1:68735913810:android:4c589fb17e10dd114db48b',
    messagingSenderId: '68735913810',
    projectId: 'betterme-43573',
    storageBucket: 'betterme-43573.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCputtTGJeSWxa3agXKoVSqatM8-yHZB8',
    appId: '1:68735913810:ios:1feca68c80e6170f4db48b',
    messagingSenderId: '68735913810',
    projectId: 'betterme-43573',
    storageBucket: 'betterme-43573.firebasestorage.app',
    iosBundleId: 'com.example.betterme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCputtTGJeSWxa3agXKoVSqatM8-yHZB8',
    appId: '1:68735913810:ios:1feca68c80e6170f4db48b',
    messagingSenderId: '68735913810',
    projectId: 'betterme-43573',
    storageBucket: 'betterme-43573.firebasestorage.app',
    iosBundleId: 'com.example.betterme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpS1SqtrRF3VurhnxR_im1TrYk7lE-RwI',
    appId: '1:68735913810:web:2964e93e9e44b53b4db48b',
    messagingSenderId: '68735913810',
    projectId: 'betterme-43573',
    authDomain: 'betterme-43573.firebaseapp.com',
    storageBucket: 'betterme-43573.firebasestorage.app',
    measurementId: 'G-NNZ1029LS3',
  );
}
